runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /Templates
  static_dir: Templates

- url: .*
  script: Main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
